import random
import uuid

class PPO_LOOP:
	def __init__(self, K: int = 6, random_sample_number: int = 40, difficulties: List[int] = [1,2], sets: List[str] = ["train", "dev"], config: Config = None):
		# number of rollouts per task
		self.K = K

		# Number of random tasks to pull per iteration
		self.random_sample_number = random_sample_number

		# Difficulty levels to include during training 
		self.difficulties = difficulties

		# Whether we train on train, dev, etc
		self.train_ids = [
		    tid
		    for dataset_name in sets
		    for tid in load_task_ids(dataset_name)
		]

		self.config = config

	def collect_rollouts(self, agent: ReactAgent) -> List[dict]:
		# Collect task ids
		task_set = random.sample(self.train_ids, self.random_sample_number)
		all_rollouts = []

		for index, task_id in enumerate(tqdm(task_set, desc=f" Running base policy rollouts for {len(task_set)} tasks")):
			print(f"\n{'='*60}")
			print(f"Task {index + 1}/{len(task_set)}: {task_id}")
			print(f"{'='*60}")

			for rollout in range(self.K):
				print(f"\n{'='*60}")
				print(f"Task {task_id} rollout: {rollout}")
				print(f"{'='*60}")
				random_uuid = uuid.uuid4()				
				task_result = {
					"task_id": task_id,
					"completed": False,
					"iterations": 0,
					"error": None,
					"result": None,
					"conversation_length": 0,
					"token_log_probs": None,
					"unit_tests": None,
					"overall_success": None,
					"uuid": random_uuid,
					"agent_state": None
				}

				try:
					# Load the appworld environment for the task
					with AppWorld(
						task_id=task_id,
						experiment_name=experiment_name,
					) as world:	
						print(f"📋 Instruction: {world.task.instruction}\n")
		                agent.initialize(
		                    first_name=world.task.supervisor.get("first_name", ""),
		                    last_name=world.task.supervisor.get("last_name", ""),
		                    email=world.task.supervisor.get("email", ""),
		                    phone_number=world.task.supervisor.get("phone_number", ""),
		                    task_instructions=world.task.instruction
		                )	

		                # Complete the task
		                agent.run(world)

		                # Collect results
		                task_result["completed"] = world.task_completed()
		                task_result["iterations"] = agent.state.iteration
		                task_result["conversation_length"] = len(agent.state.conversation_history)

		                # Only store token log probs generated by policy
						task_result["token_log_probs"] = [
						    msg.log_probs
						    for msg in agent.state.conversation_history
						    if msg.role == "assistant"
						]

						task_result["assistant_messages"] = [
						    msg.content
						    for msg in agent.state.conversation_history
						    if msg.role == "assistant"
						]

					    if world.task_completed():
					        
					        # Get performance metrics
					        evaluation = world.evaluate()
					        
					        # evaluation is a dict with:
					        # - 'overall': float (0-1, overall task success)
					        # - 'unit_tests': dict mapping unit test names to scores (0-1)
					        
					        self.state.overall_score = evaluation['overall']
					        self.state.unit_test_scores = evaluation['unit_tests']
					
		                if hasattr(world, 'get_result'):
		                    task_result["result"] = world.get_result()
		                elif hasattr(world.task, 'result'):
		                    task_result["result"] = world.task.result
		                
		                print(f"\n✅ Task completed: {task_result['completed']}")
		                print(f"🔄 Iterations: {task_result['iterations']}")
		        except Exception as e:
		            task_result["error"] = str(e)
		            print(f"\n Error: {e}")

		        # Attach the agents state to cache log probs/tokens
		        task_result["agent_state"] = agent.state

		        all_rollouts.append(task_result)

		    return all_rollouts, task_set

	def get_advantages(self, all_rollouts: List[dict], task_set: List):
		# Using equation A(c, x_k) = R(c, x_k) - (\frac{1}{K-1})\sum_{i=1}^K R(c, x_i)
		updated_rollouts = []
		for task in task_set:
			# Get all K rollouts for this task
			task_rollouts = [x for x in all_rollouts if x["task_id"] == task]

			for rollout in task_rollouts:
				# for each rollout, get advantage
				rollout_reward = rollout["unit_tests"]
				rollout_id = rollout["uuid"]

				# Get leave one out baseline reward
				baseline_reward = average([x["unit_tests"] for x in task_rollouts if x["uuid"] != rollout_id])*(1/(len(task_rollouts)-1))

				LOO_advantage = rollout_reward - baseline_reward
				rollout["advantage"] = LOO_advantage
				updated_rollouts.append(rollout)

		if len(updated_rollouts) == len(all_rollouts):
			return updated_rollouts
		else:
			raise Exception("Missing rollouts during advantage calculation")

	def shuffled_batchify(self, data, batch_size):
	    indices = list(range(len(data)))
	    random.shuffle(indices)
	    
	    for i in range(0, len(indices), batch_size):
	        batch_idx = indices[i:i + batch_size]
	        yield [data[j] for j in batch_idx]




def main():
	for iteration in range(iterations): # define in config
		# Make fresh agent
		agent = ReactAgent(config) # where are loras entering?

		try:
			# Get rollouts
			rollouts, task_set = collect_rollouts(agent)

			# Get advantages (base policy)
			updated_rollouts = get_advantages(rollouts, task_set)
		except Exception as e:
			raise Exception(f"Exception: {e}")

		# loop through tokens in outputs, calculcate loss, mini batch
		batches = 
		for epoch in epochs:
			for minibatch in shuffled_batchify(updated_rollouts, batch_size=8):
				# calculate loss
				loss = 0
				for episode in minibatch:
					for token in episode["agent_state"].conversation_history: # cycle through message list, only pull out agent messages
						








